version: '3.3'

services:
  db:
    build: .
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'stock_example'
    volumes:
      - ./data/rdbms:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-container
    volumes:
      - ./data/nosql:/data
    ports:
      - "6379:6379"
    networks:
      - db-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  db-network:
    driver: bridge
